# Generated by Django 3.2.9 on 2021-11-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата события')),
                ('views', models.BigIntegerField(blank=True, default=0, verbose_name='Количество просмотров')),
                ('clicks', models.BigIntegerField(blank=True, default=0, verbose_name='Количество кликов')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='Стоимость кликов')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистики',
            },
        ),
    ]
